# schema: https://rtx.pub/schema/rtx.json

[plugins]
# core plugins:
# go      https://github.com/jdx/rtx/blob/main/docs/go.md
# java    https://github.com/jdx/rtx/blob/main/docs/java.md
# node    https://github.com/jdx/rtx/blob/main/docs/node.md
# python  https://github.com/jdx/rtx/blob/main/docs/python.md
# ruby    https://github.com/jdx/rtx/blob/main/docs/ruby.md

[tools]
# determined from: https://go.dev/dl/
go = "1.21.4"
# determined from: https://www.python.org/downloads/
python = "3.11.6"
# determined from: https://nodejs.org/en/about/previous-releases
node = "20.10.0"
