# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

# https://sheldon.cli.rs/Examples.html#deferred-loading-of-plugins-in-zsh
[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.rm-star-silent]
inline = "setopt RM_STAR_SILENT"

# https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
[plugins.brew-completion]
inline = 'type brew &>/dev/null && FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"'

[plugins.rust-zsh-completions]
github = "ryutok/rust-zsh-completions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.wakatime-zsh-plugin]
github = "sobolevn/wakatime-zsh-plugin"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

[plugins.zoxide]
inline = 'eval "$(zoxide init zsh)"'

[plugins.direnv]
inline = 'eval "$(direnv hook zsh)"'

[plugins.mise]
inline = 'eval "$(mise activate zsh)"'
