# ref:
# starship configuration reference: https://starship.rs/config/
# inspired by Pastel Powerline Preset: https://starship.rs/presets/pastel-powerline.html
# nerd font cheat sheet: https://www.nerdfonts.com/cheat-sheet?set=nf-custom-
# One Dark Color Palette: https://www.figma.com/community/file/1137445418485757476

# pastel powerline preset
#     fg: #9A348E / #DA627D / #FCA17D / #86BBD8 / #06969A / #33658A
# piece of One Dark Pro color palette:
#     fg: #56B6C2 / #61AFEF / #C678DD / #98C379 / #E06C75 / #BE5046
#     bg: #282C34

format = """
$username[@](fg:#AAB2BF)$hostname$directory\
$git_branch$git_commit$git_state$git_status$hg_branch\
$docker_context
$character
"""
add_newline = false

[username]
show_always = true
style_user = "fg:#56B6C2"
style_root = "fg:#E06C75"
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "fg:#56B6C2"

[directory]
style = "fg:#C678DD"
read_only = "\uf023"  # nf-fa-lock
read_only_style = "fg:#ABB2BF"
format = "[$read_only]($read_only_style) [$path]($style) "
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "…/"

[git_branch]
always_show_remote = false
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "\uf418"  # octicons git_branch symbol
style = "fg:#98C379"
truncation_length = 9223372036854775807
truncation_symbol = "…"
only_attached = false
ignore_branches = []
disabled = false

[git_commit]
commit_hash_length = 7
format = '[\($hash$tag\)]($style) '
only_detached = true
tag_disabled = true
tag_max_candidates = 0
tag_symbol = " \uf412 "  # nf-oct-tag
disabled = false
style = "fg:#98C379"

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "fg:#98C379"
format = '[\($state( $progress_current/$progress_total)\) ]($style)'
disabled = false

[git_status]
# format = '([\[$all_status$ahead_behind\]]($style) )'
format = '[\[$all_status$ahead_behind\] ]($style)'
conflicted = "= "
ahead = "⇡"
behind = "⇣"
diverged = "⇕ "
up_to_date = "\uf021 "  # nf-fa-refresh
untracked = "? "
stashed = "$ "
modified = "* "
# modified = "\uf5c8"  # nf-mdi-border_color
staged = "+ "
renamed = "» "
deleted = "✘ "
style = "fg:#98C379"
ignore_submodules = false
disabled = false

[docker_context]
symbol = "\uf308"  # nf-linux-docker
style = "fg:#61AFEF"
format = ' [$symbol $context]($style)$path'

[character]
format = "$symbol "
success_symbol = "[\uf054](bold green)"     # \uf054: nf-fa-chevron_right
error_symbol = "[\uf00d \uf054](bold red)"  # \uf00d: nf-fa-remove
