# ref:
# starship configuration reference: https://starship.rs/config/
# inspired by pure theme: https://github.com/sindresorhus/pure
# nerd font cheat sheet: https://www.nerdfonts.com/cheat-sheet
# Ayu Mirage color palette: https://github.com/ayu-theme/ayu-colors

# piece of Ayu Mirage color palette:
#     fg: #707A8C / #5CCFE6 / #73D0FF / #FFAD66 / #87D96C / #F27983 / #F28779 / #DFBFFF

format = """
$username[@](fg:#707A8C)$hostname$directory\
$git_branch$git_commit$git_state$git_status$hg_branch\
$docker_context
$character
"""
add_newline = false

[username]
show_always = true
style_user = "fg:#DFBFFF"
style_root = "fg:#F27983"
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "fg:#DFBFFF"

[directory]
style = "fg:#FFAD66"
# \uf023: nf-fa-lock
read_only = "\uf023"
read_only_style = "fg:#707A8C"
format = "[$read_only]($read_only_style) [$path]($style) "
truncate_to_repo = true
truncation_length = 0

[git_branch]
always_show_remote = false
format = "[$symbol$branch(:$remote_branch)]($style) "
# \uf418: nf-oct-git_branch
symbol = "\uf418"
style = "fg:#5CCFE6"
truncation_length = 9223372036854775807
truncation_symbol = "…"
only_attached = false
ignore_branches = []
disabled = false

[git_commit]
commit_hash_length = 7
format = '[\($tag$hash\)]($style) '
only_detached = true
tag_disabled = true
tag_max_candidates = 0
# \uf412: nf-oct-tag
tag_symbol = "\uf412 "
disabled = false
style = "fg:#5CCFE6"

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "fg:#5CCFE6"
format = '[\($state( $progress_current/$progress_total)\) ]($style)'
disabled = false

[git_status]
# format = '([\[$all_status$ahead_behind\]]($style) )'
format = '[\[$all_status$ahead_behind\] ]($style)'
conflicted = "= "
ahead = "⇡"
behind = "⇣"
diverged = "⇕ "
# \uf021: nf-fa-refresh
up_to_date = "\uf021 "
untracked = "? "
stashed = "% "
modified = "* "
# \uf5c8: nf-mdi-border_color
# modified = "\uf5c8"
staged = "+ "
renamed = "» "
deleted = "✘ "
style = "fg:#5CCFE6"
ignore_submodules = false
disabled = false
# TODO: revert this
use_git_executable = true

[docker_context]
# \uf308: nf-linux-docker
symbol = "\uf308"
style = "fg:#73D0FF"
format = '[$symbol $context]($style)$path'

[character]
format = "$symbol "
# \uf054: nf-fa-chevron_right
success_symbol = "[\uf054](#87D96C)"
# \uf00d: nf-fa-remove
error_symbol = "[\uf00d \uf054](#F28779)"
