# https://rye.astral.sh/guide/config/#config-file

[default]
# This is the default build system that is used
build-system = "setuptools"

[behavior]
# When set to true the `managed` flag is always assumed to be true.
force-rye-managed = false

# Enables global shims when set to `true`. This means that the installed
# `python` shim will resolve to a Rye managed toolchain even outside of
# virtual environments.
global-python = false
