[env]
# https://rye-up.com/guide/installation/#preventing-auto-installation
RYE_NO_AUTO_INSTALL = 1

[plugins]
# core plugins:
# bun     https://mise.jdx.dev/lang/bun.html
# deno    https://mise.jdx.dev/lang/deno.html
# go      https://mise.jdx.dev/lang/go.html
# java    https://mise.jdx.dev/lang/java.html
# node    https://mise.jdx.dev/lang/node.html
# python  https://mise.jdx.dev/lang/python.html
# ruby    https://mise.jdx.dev/lang/ruby.html

rye = "https://github.com/Azuki-bar/asdf-rye.git"

[tools]
# determined from: https://github.com/denoland/deno/releases
deno = "1.39.2"
# determined from: https://go.dev/dl/
go = "1.21.4"
# determined from: https://www.python.org/downloads/
python = "3.11.6"
# determined from: https://nodejs.org/en/about/previous-releases
node = "20.10.0"
# determined from: https://github.com/mitsuhiko/rye/releases
rye = "0.22.0"
