name: Home Manager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: "nixpkgs=channel:release-23.11"
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: |
          nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
          nix-channel --update
      - run: |
          nix run nixpkgs#gnused -- -i -e "s/kh/$USER/" ./flake.nix
          nix run github:nix-community/home-manager/release-23.11 -- build --flake .
